// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const prettierRecommended = require('eslint-plugin-prettier/recommended');

module.exports = defineConfig([
  expoConfig,
  prettierRecommended,
  {
    ignores: [
      'dist/*',
      'build-ios/*',
      'build-android/*',
      'ios/*',
      'android/*',
      '.expo/*',
      'node_modules/*',
      // Generated by the Expo CLI on every start.
      'expo-env.d.ts',
    ],
  },
]);
